package com.blue.glassesapp.core.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.blue.glassesapp.core.db.entity.GlassesRecordModel;

import com.blue.glassesapp.core.db.dao.GlassesRecordModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig glassesRecordModelDaoConfig;

    private final GlassesRecordModelDao glassesRecordModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        glassesRecordModelDaoConfig = daoConfigMap.get(GlassesRecordModelDao.class).clone();
        glassesRecordModelDaoConfig.initIdentityScope(type);

        glassesRecordModelDao = new GlassesRecordModelDao(glassesRecordModelDaoConfig, this);

        registerDao(GlassesRecordModel.class, glassesRecordModelDao);
    }
    
    public void clear() {
        glassesRecordModelDaoConfig.clearIdentityScope();
    }

    public GlassesRecordModelDao getGlassesRecordModelDao() {
        return glassesRecordModelDao;
    }

}
