package com.blue.glassesapp.core.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.blue.glassesapp.core.db.entity.GlassesRecordModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GLASSES_RECORD_MODEL".
*/
public class GlassesRecordModelDao extends AbstractDao<GlassesRecordModel, Long> {

    public static final String TABLENAME = "GLASSES_RECORD_MODEL";

    /**
     * Properties of entity GlassesRecordModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Direction = new Property(1, String.class, "direction", false, "DIRECTION");
        public final static Property BusinessType = new Property(2, String.class, "businessType", false, "BUSINESS_TYPE");
        public final static Property Content = new Property(3, String.class, "content", false, "CONTENT");
        public final static Property ContentImg = new Property(4, String.class, "contentImg", false, "CONTENT_IMG");
        public final static Property Message = new Property(5, String.class, "message", false, "MESSAGE");
        public final static Property Timestamp = new Property(6, long.class, "timestamp", false, "TIMESTAMP");
    }


    public GlassesRecordModelDao(DaoConfig config) {
        super(config);
    }
    
    public GlassesRecordModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GLASSES_RECORD_MODEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"DIRECTION\" TEXT," + // 1: direction
                "\"BUSINESS_TYPE\" TEXT," + // 2: businessType
                "\"CONTENT\" TEXT," + // 3: content
                "\"CONTENT_IMG\" TEXT," + // 4: contentImg
                "\"MESSAGE\" TEXT," + // 5: message
                "\"TIMESTAMP\" INTEGER NOT NULL );"); // 6: timestamp
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GLASSES_RECORD_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GlassesRecordModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String direction = entity.getDirection();
        if (direction != null) {
            stmt.bindString(2, direction);
        }
 
        String businessType = entity.getBusinessType();
        if (businessType != null) {
            stmt.bindString(3, businessType);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(4, content);
        }
 
        String contentImg = entity.getContentImg();
        if (contentImg != null) {
            stmt.bindString(5, contentImg);
        }
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(6, message);
        }
        stmt.bindLong(7, entity.getTimestamp());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GlassesRecordModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String direction = entity.getDirection();
        if (direction != null) {
            stmt.bindString(2, direction);
        }
 
        String businessType = entity.getBusinessType();
        if (businessType != null) {
            stmt.bindString(3, businessType);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(4, content);
        }
 
        String contentImg = entity.getContentImg();
        if (contentImg != null) {
            stmt.bindString(5, contentImg);
        }
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(6, message);
        }
        stmt.bindLong(7, entity.getTimestamp());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GlassesRecordModel readEntity(Cursor cursor, int offset) {
        GlassesRecordModel entity = new GlassesRecordModel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // direction
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // businessType
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // content
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // contentImg
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // message
            cursor.getLong(offset + 6) // timestamp
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GlassesRecordModel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDirection(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBusinessType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setContent(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setContentImg(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMessage(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTimestamp(cursor.getLong(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GlassesRecordModel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GlassesRecordModel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GlassesRecordModel entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
